---
title: "Basic Statistics with R"
author: "Alvaro Fuentes"
date: "April, 2016"
output: html_document
---

# Basic Statistical Functions

## Loading the data
```{r, warning= FALSE}
library(ggplot2)
path_to_file <- 'https://raw.githubusercontent.com/quantcompany/Springboard_FDS/master/DiabetesR.csv'
diabetes <- read.csv(path_to_file, stringsAsFactors = FALSE)
diabetes$frame <- factor(diabetes$frame)
diabetes$gender <- factor(diabetes$gender)
```

## Descriptive Statistics

### Descriptive Statistics for a Numerical Variable
```{r, warning= FALSE}
# For numerical variables

summary(diabetes$hdl)
mean(diabetes$hdl, na.rm = TRUE)
median(diabetes$hdl, na.rm = TRUE)
sd(diabetes$hdl, na.rm = TRUE)
quantile(x = diabetes$hdl, probs = seq(0,1, by = 0.05), na.rm = TRUE)
min(diabetes$hdl, na.rm = TRUE)
max(diabetes$hdl, na.rm = TRUE)
hist(diabetes$hdl, main = "HDL Levels", breaks = 20)

# Some Visualization
ggplot(diabetes) + 
    geom_histogram(aes(x = Cholesterol), fill = "white", color = "blue") + 
    ggtitle("Cholesterol")

ggplot(diabetes) + 
    geom_density(aes(x = Cholesterol), color = "blue") + 
    ggtitle("Cholesterol")

```

### Descriptive Statistics for a Categorical Variable
```{r, warning= FALSE}

table(diabetes$frame)
table(diabetes$frame)/sum(table(diabetes$frame))

ggplot(diabetes) + 
    geom_bar(aes(x = frame)) + 
    ggtitle("Frame")

# Removing the NA's bar
ggplot(diabetes[!is.na(diabetes$frame),]) + 
    geom_bar(aes(x = frame)) + 
    ggtitle("Frame")

```


## Visualization for Two Variables

```{r, warning= FALSE}

# Two numerical variables
ggplot(diabetes) + 
    geom_point(aes(x = Cholesterol, y = weight))

# Numerical vs. Categorical
ggplot(diabetes) + 
    geom_boxplot(aes(x = gender, y = Cholesterol))

ggplot(diabetes) + 
    geom_density(aes(x = Cholesterol, fill = gender), alpha = 0.4)

ggplot(diabetes) + 
    geom_density(aes(x = height, fill = gender), alpha = 0.3)


# Categorical vs. Categorical
ggplot(diabetes[!is.na(diabetes$frame),]) + 
    geom_bar(aes(x = gender, fill = frame), position = 'dodge')

ggplot(diabetes[!is.na(diabetes$frame),]) + 
    geom_bar(aes(x = gender, fill = frame), position = 'stack')

ggplot(diabetes[!is.na(diabetes$frame),]) + 
    geom_bar(aes(x = gender, fill = frame), position = 'fill')
```


## Basic inference

```{r, warning= FALSE}
# Confidence interval for the means for numerical variables
t.test(diabetes$hdl, conf.level = 0.95)
# hipothesis test for the mean (nul_mu = 55)
t.test(diabetes$hdl, mu = 55, conf.level = 0.95)


# For categorical variables
table(diabetes$frame)
table(diabetes$frame)/sum(table(diabetes$frame))
# Confidence interval for the proportion of individuals with 'small' frames
prop.test(x = 104, n = (104+184+103))

# Equality of variances
bartlett.test(diabetes$hdl ~ diabetes$frame)

# Equality of medians (centrality parameter)
kruskal.test(diabetes$hdl ~ diabetes$frame)

# Correlations
cor(diabetes$hdl, diabetes$Cholesterol, use = 'pairwise.complete')
# Correlation Matrix
cor(diabetes[,c('hdl', 'Cholesterol','ratio','bp.1s')], use = 'pairwise.complete')

# Confidence intervals for correlations (and test for correlations)
cor.test(diabetes$hdl, diabetes$Cholesterol)

```


## Simulation

```{r, warning= FALSE}
# Random sample
sample(diabetes$Cholesterol, size = 50, replace = FALSE)

# Simulating 60 tosses of an unfair coin (75% of getting tails)
sample(c('heads','tails'), size = 60, replace = TRUE, prob = c(0.25,0.75))

# Random numbers and distributions
# Density
pnorm(q = seq(70,130, by = 1), mean = 100, sd = 15)
# Quantiles
qnorm(p = c(0.25,0.5,0.95), mean = 100, sd = 15)
# CDF (the inverse of quantile function)
pnorm(q = c(89.88265, 100, 124.67280), mean = 100, sd = 15)

#20 normal random numbers, mean = 100, sd = 15
rnorm(20, mean = 100, sd = 15)


```
For more information on other statistical  distributions and funtions in r, take a look at [this presentation](http://www.biostat.jhsph.edu/~hji/courses/statcomputing/StatFunc.pdf)
